version: '3.1'

services:
  comments:
    build: ./comments
    ports:
      - "4001:3000"
  event-bus:
    build: ./event-bus
    ports:
      - "4005:3000"
  moderation:
    build: ./moderation
    ports:
      - "4003:3000"
  posts:
    build: ./posts
    ports:
      - "4000:3000"
  queries:
    build: ./queries
    ports:
      - "4002:3000"
 